import Head from 'next/head'
import { PaymentForm } from '@/components'

export default function Home() {
  return (
    <>
      <Head>
        <title>MOO | xState playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container py-12 flex justify-center items-center flex-col">
        <h1 className='text-3xl text-center mb-12'>xState Playground</h1>

        <PaymentForm />
      </main>
    </>
  )
}
